pipeline:
  deps:
    image: node:18
    commands:
      - corepack enable
      - corepack prepare yarn@3.2.2 --activate
      - yarn
    when:
      event: [push, tag, deployment, manual]

  publish:
    image: node:18
    pull: true
    commands:
      - corepack enable
      - corepack prepare yarn@3.2.2 --activate
      - yarn build
      - git clone https://osfanbuff63:@$${push_token}codeberg.org/osfanbuff63/pages /tmp/pages
      - git -C /tmp/pages switch -C main
      - mv /tmp/pages/.git build
      - cd build
      - git config user.email "automation+noreply@osfanbuff63.tech" ; git config user.name "Website Updater"
      - git add .
      - git diff-index --quiet HEAD || git commit -m 'publish' -a
      - git push --force origin main
    when:
      event: [push, manual]
      branch: main
    secrets:
      - push_token
